### PR TITLE
Write $experiments values to all pending events.

### PR DESCRIPTION
**Pull request by DawnWright**
We 'joinExperiments' with Mixpanel when we start our app, prior to queuing any analytics events. Therefore, our desire is that any events we queue will have the $experiments super property attached, indicating which experiment variants are running in this app session. Having this super property in place on all events is key to our data analysis. But there is a race condition in Mixpanel that causes the super property to be missing from our early events.

Mixpanel doesn't set the $experiments super property until it receives a response back from the network request to obtain the experiment variants. Mixpanel uses a serial dispatch queue for all data to ensure proper ordering. So after the experiments network request returns, Mixpanel queues a block to set the $experiments property. Our pending events then get processed by the queue and wind up missing this super property, because the super property isn't actually set until after the queued events are processed in the queue.

By setting $experiments immediately instead of queuing, it will get applied to all queued events (which by definition were added after 'joinExperiments' was called).

PTAL @floatplane @julianwa @petersibley

### CODE REVIEW

**Comment by DawnWright** [comment]
View the diff with whitespace ignored: https://github.com/FiftyThree/mixpanel-iphone/pull/1/files?w=1

**Comment by floatplane** [comment]
I guess my only question is whether there's a potential for race conditions being introduced here. Are Mixpanel expecting that `self.superProperties` will be written and read on multiple threads, or are they counting on it only being read while executing on that serial dispatch queue? In that light, this is a pretty big behavior change.

One way to make that safer would be to queue a block to `self.serialQueue` that waits for a condition_variable to get flipped. Now your queue is frozen until you choose to release it, and maybe you can feel better about touching internals on a different thread. But that's starting to get a lot more invasive.

I don't know, I guess I have to say LRTM BISFSS (looks reasonable to me, but I still feel slightly scared).

**Comment by DawnWright** [comment]
> are they counting on it only being read while executing on that serial dispatch queue?

I believe they are counting on that. markVariantRun is only ever called from that serial dispatch queue, so we should still be good in that regard.

I realize this is totally unclear and requires a careful read of their code, and I was thinking about asserting this in the way that I do in UnlockedToolsReceipt.mm with dispatch_queue_set_specific/dispatch_get_specific, but was also aiming to keep the change as minimal as possible.

**Comment by DawnWright** [comment]
I eat my words. It is only called from the serial queue in our scenario, but not in another code path.

**Comment by DawnWright** [comment]
From what I can tell, our discussion points out that they have another threading issue going on. The following bit of code can be called from both main and background threads:

        for (MPVariant *variant in newVariants) {
            [variant execute];
            [self markVariantRun:variant];
        }

From my read of their code, it seems like variants must be executed on the main thread, since this calls back into the client. And superProperties must be accessed via the serialQueue. But they are not doing this in joinExperiments, which is actually executing the variants on the serial dispatch queue.

This is an existing issue with joinExperiments, even without my changes, and I'm not yet clear on the implications for us, since that's our way of starting experiments. Agreed on the feeling slightly scared.

**Comment by petersibley** [comment]
Looks reasonable. It sounds like the threading story here is more convoluted than I'd like for a last minute fix. Maybe make a PR against them and ping our engineering contacts?

**Comment by DawnWright** [comment]
Agreed. I was talking with their technical support guy throughout yesterday. He agrees it's a significant issue and is talking with their engineering team. I'm certain my proposed fix isn't the right long-term solution here, so it's not a change they can take. I have a different solution for this release, here: https://github.com/FiftyThree/mixpanel-iphone/pull/2

**Pull request closed without merging**
